### ISSUE TITLE
[ENH]: Support `gh auth switch`

### ISSUE THREAD

**Issue by anstadnik** [2KAbhishek/octohub.nvim#4]
### Description

gh cli supports multiple users. Because of that, you should probably check if the cache is for the previous user, and reload it if not. Now, it seems, that repos are cached, even when the user is changed

**Comment by 2KAbhishek** [comment]
I have added `prefix` support to the clear cache command.

You can now clear the username cache using the `:UtilsClearCache username` command.
Checking for username before every command will be expensive/slow.

I am closing the issue for now, thanks for the suggestion
