### ISSUE TITLE
[BUG]: projects_dir is ignored

### ISSUE THREAD

**Issue by al1-ce** [2KAbhishek/octohub.nvim#6]
### Description of the bug

See title and steps

### Steps To Reproduce

- Default config with `projects_dir = "/g"`
- `<leader>goo`
- `<cr>` on any repo
- repo is cloned to ~/Projects and not set dir

**Comment by 2KAbhishek** [comment]
Thanks for reporting, I'll take a look

**Comment by al1-ce** [comment]
Nope, solution is quite simple actually

Your "plugin/octohub.lua" is called before any setup it seems which takes default config and applies it

I'll submit PR with fix
